(let ((my-c-style 
        '((c-tab-always-indent        . t)
          (indent-tabs-mode           . nil)
          (c-tab-width                . 4)
          (c-basic-offset             . 4)
          (c-comment-only-line-offset . 0)
          (c-hanging-braces-alist     . ((substatement-open after)
                                         (brace-list-open)))
          (c-hanging-colons-alist     . ((member-init-intro before)
                                         (inher-intro)
                                         (case-label after)
                                         (label after)
                                         (access-label after)))
          (c-cleanup-list             . (scope-operator
                                         empty-defun-braces
                                         defun-close-semi))
          (c-offsets-alist            . ((arglist-close . c-lineup-arglist)
                                         (substatement-open . 0)
                                         (case-label        . 4)
                                         (block-open        . 0)
                                         (knr-argdecl-intro . -)))
          (c-echo-syntactic-information-p . t)))
      (my-linux-c-style
       '((c-tab-always-indent        . t)
         (indent-tabs-mode           . t)
         (c-tab-width                . 8)
         (c-basic-offset             . 8)
         (tab-width                  . 8)
         (c-comment-only-line-offset . 0)
         (c-hanging-braces-alist     . ((substatement-open after)
                                        (brace-list-open)))
         (c-hanging-colons-alist     . ((member-init-intro before)
                                        (inher-intro)
                                        (case-label after)
                                        (label after)
                                        (access-label after)))
         (c-cleanup-list             . (scope-operator
                                        empty-defun-braces
                                        defun-close-semi))
         (c-offsets-alist            . ((arglist-close . c-lineup-arglist)
                                        (substatement-open . 0)
                                        (case-label        . 0)
                                        (block-open        . 0)
                                        (knr-argdecl-intro . -)))
         (c-echo-syntactic-information-p . t))))
    (c-add-style "my" my-c-style)
    (c-add-style "linux-kernel" my-linux-c-style))
